package com.time.scenery.rain.space.mybatis.daoentity;

public class RentReportConfigLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.uuid_id
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String uuidId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.my_key
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String myKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.rent_tab_name
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String rentTabName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.start_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.end_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.remark
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.my_value
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String myValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.status
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_report_config_log.update_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.uuid_id
     *
     * @return the value of rent_report_config_log.uuid_id
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getUuidId() {
        return uuidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.uuid_id
     *
     * @param uuidId the value for rent_report_config_log.uuid_id
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setUuidId(String uuidId) {
        this.uuidId = uuidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.my_key
     *
     * @return the value of rent_report_config_log.my_key
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getMyKey() {
        return myKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.my_key
     *
     * @param myKey the value for rent_report_config_log.my_key
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setMyKey(String myKey) {
        this.myKey = myKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.rent_tab_name
     *
     * @return the value of rent_report_config_log.rent_tab_name
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getRentTabName() {
        return rentTabName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.rent_tab_name
     *
     * @param rentTabName the value for rent_report_config_log.rent_tab_name
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setRentTabName(String rentTabName) {
        this.rentTabName = rentTabName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.start_time
     *
     * @return the value of rent_report_config_log.start_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.start_time
     *
     * @param startTime the value for rent_report_config_log.start_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.end_time
     *
     * @return the value of rent_report_config_log.end_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.end_time
     *
     * @param endTime the value for rent_report_config_log.end_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.remark
     *
     * @return the value of rent_report_config_log.remark
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.remark
     *
     * @param remark the value for rent_report_config_log.remark
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.my_value
     *
     * @return the value of rent_report_config_log.my_value
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getMyValue() {
        return myValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.my_value
     *
     * @param myValue the value for rent_report_config_log.my_value
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setMyValue(String myValue) {
        this.myValue = myValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.status
     *
     * @return the value of rent_report_config_log.status
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.status
     *
     * @param status the value for rent_report_config_log.status
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_report_config_log.update_time
     *
     * @return the value of rent_report_config_log.update_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_report_config_log.update_time
     *
     * @param updateTime the value for rent_report_config_log.update_time
     *
     * @mbggenerated Wed Oct 18 15:42:57 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}